VoyageCalc/urls.py
from django.conf.urls import url
from django.views.generic import ListView

from . import views
from .models import Charterer, Port, Vessel, Chart, Voyage, Income

urlpatterns = [
    # startpage
    url(r'^$', views.home, name='home'),

    #charterer urls
    url(r'^create_charterer/$', views.create_charterer, name='create_charterer'),
    url(r'^charterer_list/$', ListView.as_view(queryset=Charterer.objects.all().order_by('company_name'), template_name="VoyageCalc/charterer_list.html"), name='charterer-list'),
    url(r'^(?P<id>[0-9]+)/edit_charterer$', views.edit_charterer, name='edit-charterer'),

    # port urls
    url(r'^create_port/$', views.create_port, name='create_port'),
    url(r'^port_list/$', ListView.as_view(queryset=Port.objects.all().order_by('port_name'), template_name="VoyageCalc/port_list.html"), name='port-list'),
    url(r'^(?P<id>[0-9]+)/edit_port$', views.edit_port, name='edit-port'),

    # vessel urls
    url(r'^create_vessel/$', views.create_vessel, name='create_vessel'),
    url(r'^vessel_list/$', ListView.as_view(queryset=Vessel.objects.all().order_by('vessel_name'), template_name="VoyageCalc/vessel_list.html"), name='vessel-list'),
    url(r'^(?P<id>[0-9]+)/edit_vessel$', views.edit_vessel, name='edit-vessel'),

    # chart urls
    url(r'^create_chart/$', views.create_chart, name='create_chart'),
    url(r'^chart_list/$', ListView.as_view(queryset=Chart.objects.filter(finished=False).order_by('-id'), template_name="VoyageCalc/chart_list.html"), name='chart-list'),
    url(r'^chart_list_finished/$', ListView.as_view(queryset=Chart.objects.filter(finished=True).order_by('-id'), template_name="VoyageCalc/chart_list_finished.html"), name='finished-charts'),
    url(r'^(?P<id>[0-9]+)/edit_chart$', views.edit_chart, name='edit-chart'),
    
    # voyage urls
    url(r'^create_voyage/$', views.create_voyage, name='create_voyage'),
    url(r'^voyage_list/$', ListView.as_view(queryset=Voyage.objects.filter(finished=False).order_by('-id'), template_name="VoyageCalc/voyage_list.html"), name='voyage-list'),
    url(r'^voyage_list_finished/$', ListView.as_view(queryset=Voyage.objects.filter(finished=True).order_by('-id'), template_name="VoyageCalc/voyage_list_finished.html"), name='finished-voyages'),
    url(r'^(?P<id>[0-9]+)/edit_voyage$', views.edit_voyage, name='edit-voyage'),

    # cost & income urls
    url(r'^(?P<id>[0-9]+)/add_income/$', views.add_income, name='add_income'),
    url(r'^(?P<id>[0-9]+)/add_cost/$', views.add_cost, name='add_cost'),
    ]

carten/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from .settings import BASE_DIR, STATIC_ROOT



admin.autodiscover()

print('base_dir: ', BASE_DIR, '\nstatic_root: ', STATIC_ROOT)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('VoyageCalc.urls', namespace='VoyageCalc')),

    # Registration redux 
    url(r'^accounts/', include('registration.backends.default.urls')),]

carten/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>{% block title %}{% endblock title %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Tangerine">
  {% block header %}
  {% endblock header %}

    {% block style %}
        <link rel="stylesheet" type="text/css" href="{% static 'VoyageCalc/style.css' %}" />
    {% endblock style %}


    <!-- Latest compiled and minified JavaScript -->
</head>
<body data-spy="scroll" data-target="#spy-scroll-id">

<!-- <nav class="navbar navbar-default navbar-fixed-top" style="margin-bottom:15px;">-->
<nav class="navbar navbar-inverse navbar-fixed-top" style="margin-bottom:15px;">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#spy-scroll-id">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'VoyageCalc:home' %}">C-Calc</a>
        </div>

        <!-- Items -->

        <div class="collapse navbar-collapse" id="spy-scroll-id">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                <li class="">
                    <a href="{% url 'VoyageCalc:voyage-list' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;
                        Voyages
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'VoyageCalc:chart-list' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;
                        Charts
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'VoyageCalc:vessel-list' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;
                        Vessels
                    </a>
                </li>
                
                
                <li class="">
                    <a href="{% url 'VoyageCalc:port-list' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                        Ports
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'VoyageCalc:charterer-list' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;
                        Charterers
                    </a>
                </li>
                {% endif %}
            
            </ul>

            
            <ul class="nav navbar-nav navbar-right">

                {% if user.is_authenticated %}
                <li class="">
                    <a href="{% url 'VoyageCalc:create_voyage' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Voyage
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'VoyageCalc:create_chart' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Chart
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'VoyageCalc:create_vessel' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Vessel
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'VoyageCalc:create_port' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Port
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'VoyageCalc:create_charterer' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Charterer
                    </a>
                </li>
                {% endif %}

                {% if user.is_authenticated %}
                <li class="">
                    <a href="{% url 'auth_logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Log out
                    </a>
                </li>
                {% else %}
                <li class="">
                    <a href="{% url 'auth_login' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Log in
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'registration_register' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Register
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <style>
        body{

    padding-top:140px;
}
    </style>
<!-- {% if user.is_authenticated %}
 <div class="alert alert-danger" role="alert" align="center">
    <strong><a href="{% url 'VoyageCalc:chart-list' %}">Carten Maria!</a></strong> Nearing end of chart!!
</div>
{% endif%}
</div> -->
</nav>




{% block body %}

{% endblock body %}


{% block footer %}
{% if request.user.is_authenticated %}
<div class="footer navbar-fixed-bottom" style="text-align:right"><a href="mailto:sten_terje@hotmail.com?Subject=Hei%20fra%20{{request.user}}" target="_top"><button class="btn btn-default btn-sm">
<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;E-mail RUTER-IT</button></a></div>

{% endif %}
{% endblock footer %}
<!-- Latest compiled and minified JavaScript -->
<!--<script src="https://ajax.goolgeapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script data-cfasync="false" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script data-cfasync="false" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>
<script data-cfasync="false" src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src=""></script>
</body>
</html>