VoyageCalc/urls.py
from django.conf.urls import url
from django.views.generic import ListView

from . import views
from .models import Charterer, Port, Vessel, Chart, Voyage, Income

urlpatterns = [
    # startpage
    url(r'^$', views.home, name='home'),

    #charterer urls
    url(r'^create_charterer/$', views.create_charterer, name='create_charterer'),
    url(r'^charterer_list/$', ListView.as_view(queryset=Charterer.objects.all().order_by('company_name'), template_name="VoyageCalc/charterer_list.html"), name='charterer-list'),
    url(r'^(?P<id>[0-9]+)/edit_charterer$', views.edit_charterer, name='edit-charterer'),

    # port urls
    url(r'^create_port/$', views.create_port, name='create_port'),
    url(r'^port_list/$', ListView.as_view(queryset=Port.objects.all().order_by('port_name'), template_name="VoyageCalc/port_list.html"), name='port-list'),
    url(r'^(?P<id>[0-9]+)/edit_port$', views.edit_port, name='edit-port'),

    # vessel urls
    url(r'^create_vessel/$', views.create_vessel, name='create_vessel'),
    url(r'^vessel_list/$', ListView.as_view(queryset=Vessel.objects.all().order_by('vessel_name'), template_name="VoyageCalc/vessel_list.html"), name='vessel-list'),
    url(r'^(?P<id>[0-9]+)/edit_vessel$', views.edit_vessel, name='edit-vessel'),

    # chart urls
    url(r'^create_chart/$', views.create_chart, name='create_chart'),
    url(r'^chart_list/$', ListView.as_view(queryset=Chart.objects.filter(finished=False).order_by('-id'), template_name="VoyageCalc/chart_list.html"), name='chart-list'),
    url(r'^chart_list_finished/$', ListView.as_view(queryset=Chart.objects.filter(finished=True).order_by('-id'), template_name="VoyageCalc/chart_list_finished.html"), name='finished-charts'),
    url(r'^(?P<id>[0-9]+)/edit_chart$', views.edit_chart, name='edit-chart'),
    
    # voyage urls
    url(r'^create_voyage/$', views.create_voyage, name='create_voyage'),
    url(r'^voyage_list/$', ListView.as_view(queryset=Voyage.objects.filter(finished=False).order_by('-id'), template_name="VoyageCalc/voyage_list.html"), name='voyage-list'),
    url(r'^voyage_list_finished/$', ListView.as_view(queryset=Voyage.objects.filter(finished=True).order_by('-id'), template_name="VoyageCalc/voyage_list_finished.html"), name='finished-voyages'),
    url(r'^(?P<id>[0-9]+)/edit_voyage$', views.edit_voyage, name='edit-voyage'),

    # cost & income urls
    url(r'^(?P<id>[0-9]+)/add_income/$', views.add_income, name='add_income'),
    url(r'^(?P<id>[0-9]+)/add_cost/$', views.add_cost, name='add_cost'),
    ]

carten/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from .settings import BASE_DIR, STATIC_ROOT



admin.autodiscover()

print('base_dir: ', BASE_DIR, '\nstatic_root: ', STATIC_ROOT)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('VoyageCalc.urls', namespace='VoyageCalc')),

    # Registration redux 
    url(r'^accounts/', include('registration.backends.default.urls')),]

VoyageCalc/forms.py
from django import forms
from .models import Charterer, Port, Vessel, Chart, Voyage, Income, Cost
import datetime
from datetime import date, datetime

class ChartererCreateForm(forms.ModelForm):

    class Meta:
        model = Charterer
        exclude = [
                'created_by',
                'created',
                'updated',
                'deleted',
        ]

class PortCreateForm(forms.ModelForm):

    class Meta:
        model = Port
        exclude = [
                'created_by',
                'created',
                'updated',
                'deleted',
        ]

class VesselCreateForm(forms.ModelForm):

    cons_lad = forms.FloatField(label='Consumption Laden')
    cons_bal = forms.FloatField(label='Consumption Ballast')
    cons_por_mgo = forms.FloatField(label='Consumption Port MGO')
    cons_por_ifo = forms.FloatField(label='Consumption Port IFO')

    class Meta:
        model = Vessel
        exclude = [
                   'created',
                   'created_by',
                   'updated',
                   'deleted',
        ]

class ChartCreateForm(forms.ModelForm):

    date_start = forms.DateField(widget=forms.DateInput, initial='ie. 12 apr 1977')
    date_end = forms.DateField(widget=forms.DateInput, initial='ie. 12 apr 1977')
    
    class Meta:
        model = Chart
        exclude = [
                'created_by',
                'updated_by',
                'created',
                'finished',
                'updated',
                'deleted',
        ]

class ChartEditForm(forms.ModelForm):

    date_start = forms.DateField(widget=forms.DateInput, initial='ie. 12 apr 1977')
    date_end = forms.DateField(widget=forms.DateInput, initial='ie. 12 apr 1977')
    
    class Meta:
        model = Chart
        exclude = [
                'created_by',
                'updated_by',
                'created',
                'updated',
                'deleted',
        ]

class VoyageCreateForm(forms.ModelForm):

    chart = forms.ModelChoiceField(queryset=Chart.objects.all(), empty_label=None)
    vessel = forms.ModelChoiceField(queryset=Vessel.objects.all(), empty_label=None)

    date_start = forms.DateField()
    date_end = forms.DateField()

    comment = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:   
        model = Voyage
        exclude = [
                'created_by',
                'created',
                'updated_by',
                'updated',
    ]

class IncomeForm(forms.ModelForm):

    INCOME_TYPES = (
                ('LS','Freight Lumpsum'),
                ('TFI', 'Total Freight Income'),
                ('OFI','Other Freight Incomes'),
                ('DD', 'Demurrage/Despatch'),
        )
    income_type = forms.ChoiceField(choices=INCOME_TYPES)

    CURRENCY = (
            ('USD','US Dollar'),
            ('EUR','Euro'),
            ('SEK','Swedish Krone'),
            ('DKK','Danisk Krone'),
            ('NOK','Norw Krone'),
            )
    currency = forms.ChoiceField(choices=CURRENCY, initial='NOK')

    class Meta:   
        model = Income
        fields = [
                    'currency',
                    'exchange_rate',
                    'income_type',
                    'income_amount',
        ]

class CostForm(forms.ModelForm):

    class Meta:   
        model = Cost
        fields = [
                    'currency',
                    'exchange_rate',
                    'cost_type',
                    'cost_amount',
        ]


    COST_TYPES = (
                ('PD','Port Dispursement'),
                ('ME','Misc. Expenses'),
                ('BU', '* Bunkers *'),
                ('CO', '* Commission *')
        )

    cost_type = forms.ChoiceField(choices=COST_TYPES)

    CURRENCY = (
                ('USD','US Dollar'),
                ('EUR','Euro'),
                ('SEK','Swedish Krone'),
                ('DKK','Danisk Krone'),
                ('NOK','Norw Krone'),
                )
    currency = forms.ChoiceField(choices=CURRENCY, initial='NOK')

VoyageCalc/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Charterer, Port, Vessel, Chart, Voyage, Income, Cost
from .forms import ChartererCreateForm, PortCreateForm, VesselCreateForm, ChartCreateForm, ChartEditForm, VoyageCreateForm, IncomeForm, CostForm
import random
from django.contrib.auth.models import User
from carten import settings
from django.utils.http import is_safe_url

app_name='VoyageCalc'


def home(request):
    title = "C-Calc"
    version = settings.VERSION

    pic_num = random.randrange(1, 4)

    user = request.user
    if not user.is_authenticated:
       return redirect('auth_login')
    context = {
        'title': title,
        'pic_num': pic_num,
        'version': version, 
    }
    return render(request, 'VoyageCalc/home.html', context)

# Charterer views
def create_charterer(request):
    title = 'New Charterer'
    form = ChartererCreateForm(request.POST or None)
    user = request.user
    sub_btn = "Add Charterer"
    
    if not user.is_authenticated:
        return redirect('/')
    
    if form.is_valid():
        user_logged_in = request.user
        charterer = form.save(commit=False)

        # automatic set created_by
        created_by = user_logged_in
        charterer.created_by = created_by

        # insert form data to object
        company_name = form.cleaned_data.get('company_name')
        split_name = company_name.split(" ")
        company_name = ""
        for i in split_name:
            company_name += (i.capitalize()) + " "
        charterer.company_name = company_name
        
        contact_person = form.cleaned_data.get('contact_person')
        charterer.contact_person = contact_person

        address = form.cleaned_data.get('address')
        charterer.address = address

        country = form.cleaned_data.get('country')
        charterer.country = country

        switch_board = form.cleaned_data.get('switch_board')
        charterer.switch_board = switch_board

        comment = form.cleaned_data.get('comment')
        charterer.comment = comment

        charterer.save()

        return redirect("VoyageCalc:charterer-list")

    context = {
        'form': form,
        'title': title,
        'sub_btn': sub_btn,
    }

    return render(request, "VoyageCalc/form.html", context)

def edit_charterer(request, id=None):
    title = 'Update Charterer'
    charterer = Charterer.objects.get(id=id)
    form = ChartererCreateForm(request.POST or None, instance=charterer)
    user = request.user
    sub_btn = "Update"
    
    if not user.is_authenticated:
        return redirect('/')
    
    if form.is_valid():
        user_logged_in = request.user
        charterer = form.save(commit=False)

        # automatic set created_by
        created_by = user_logged_in
        charterer.created_by = created_by

        # insert form data to object
        company_name = form.cleaned_data.get('company_name')
        split_name = company_name.split(" ")
        company_name = ""
        for i in split_name:
            company_name += (i.capitalize()) + " "
        charterer.company_name = company_name

        contact_person = form.cleaned_data.get('contact_person')
        charterer.contact_person = contact_person
        
        address = form.cleaned_data.get('address')
        charterer.address = address

        country = form.cleaned_data.get('country')
        charterer.country = country

        switch_board = form.cleaned_data.get('switch_board')
        charterer.switch_board = switch_board

        comment = form.cleaned_data.get('comment')
        charterer.comment = comment

        charterer.save()

        return redirect("VoyageCalc:charterer-list")

    context = {
        'form': form,
        'title': title,
        'sub_btn': sub_btn,
    }

    return render(request, "VoyageCalc/form.html", context)

# port views
def create_port(request):
    title = 'New Port'
    form = PortCreateForm(request.POST or None)
    user = request.user
    sub_btn = "Add Port"
    
    if not user.is_authenticated:
        return redirect('/')
    

    if form.is_valid():
        user_logged_in = request.user
        port = form.save(commit=False)

        # automatic set created_by
        created_by = user_logged_in
        port.created_by = created_by

        # insert form data to object
        port_name = form.cleaned_data.get('port_name')
        split_name = port_name.split(" ")
        port_name = ""
        for i in split_name:
            port_name += (i.capitalize()) + " "
        port.port_name = port_name
        
        price = form.cleaned_data.get('price')
        port.price = price

        try:
            contact_person = form.cleaned_data.get('contact_person')
            split_name = contact_person.split(" ")
            contact_person = ""
            for i in contact_person:
                contact_person += (i.capitalize()) + " "
            port.contact_person = contact_person
        except AttributeError:
            pass


        telephone = form.cleaned_data.get('telephone')
        port.telephone = telephone

        comment = form.cleaned_data.get('comment')
        port.comment = comment

        port.save()

        return redirect("VoyageCalc:port-list")

    context = {
        'form': form,
        'title': title,
        'sub_btn': sub_btn,
    }

    return render(request, "VoyageCalc/form.html", context)

def edit_port(request, id=None):
    user = request.user
    if not user.is_authenticated:
        return redirect('/')

    title = 'Update Port'
    sub_btn = "Update"
    port = Port.objects.get(id=id)
    form = PortCreateForm(request.POST or None, instance=port)
    

    if form.is_valid():
        port = form.save(commit=False)

        # automatic set created_by
        created_by = user
        port.created_by = created_by

        # insert form data to object
        port_name = form.cleaned_data.get('port_name')
        split_name = port_name.split(" ")
        port_name = ""
        for i in split_name:
            port_name += (i.capitalize()) + " "
        port.port_name = port_name
        
        price = form.cleaned_data.get('price')
        port.price = price

        try:
            contact_person = form.cleaned_data.get('contact_person')
            split_name = contact_person.split(" ")
            contact_person = ""
            for i in contact_person:
                contact_person += (i.capitalize()) + " "
            port.contact_person = contact_person
        except AttributeError:
            pass

        telephone = form.cleaned_data.get('telephone')
        port.telephone = telephone

        comment = form.cleaned_data.get('comment')
        port.comment = comment

        port.save()

        return redirect("VoyageCalc:port-list")

    context = {
        'form': form,
        'title': title,
        'sub_btn': sub_btn,
    }

    return render(request, "VoyageCalc/form.html", context)

# vessel views
def create_vessel(request):
    title = 'New Vessel'
    form = VesselCreateForm(request.POST or None)
    user = request.user
    sub_btn = "Add Vessel"
    
    if not user.is_authenticated:
        return redirect('/')
    

    if form.is_valid():
        user_logged_in = request.user
        vessel = form.save(commit=False)

        # automatic set created_by
        created_by = user_logged_in
        vessel.created_by = created_by

        # insert form data to object
        vessel_name = form.cleaned_data.get('vessel_name')
        split_name = vessel_name.split(" ")
        vessel_name = ""
        for i in split_name:
            vessel_name += (i.capitalize()) + " "
        vessel.vessel_name = vessel_name

        telephone = form.cleaned_data.get('telephone')
        vessel.telephone = telephone
        
        cons_lad = form.cleaned_data.get('cons_lad')
        vessel.cons_lad = cons_lad

        cons_bal = form.cleaned_data.get('cons_bal')
        vessel.cons_bal = cons_bal

        cons_por_mgo = form.cleaned_data.get('cons_por_mgo')
        vessel.cons_por_mgo = cons_por_mgo

        cons_por_ifo = form.cleaned_data.get('cons_por_ifo')
        vessel.cons_por_ifo = cons_por_ifo

        comment = form.cleaned_data.get('comment')
        vessel.comment = comment

        vessel.save()

        return redirect("VoyageCalc:vessel-list")

    context = {
        'form': form,
        'title': title,
        'sub_btn': sub_btn,
    }

    return render(request, "VoyageCalc/form.html", context)

def edit_vessel(request, id=None):
    title = 'Update Vessel'
    vessel = Vessel.objects.get(id=id)
    form = VesselCreateForm(request.POST or None, instance=vessel)
    user = request.user
    sub_btn = "Update"
    
    if not user.is_authenticated:
        return redirect('/')
    

    if form.is_valid():
        user_logged_in = request.user
        vessel = form.save(commit=False)

        # automatic set created_by
        created_by = user_logged_in
        vessel.created_by = created_by

        # insert form data to object
        vessel_name = form.cleaned_data.get('vessel_name')
        split_name = vessel_name.split(" ")
        vessel_name = ""
        for i in split_name:
            vessel_name += (i.capitalize()) + " "
        vessel.vessel_name = vessel_name

        telephone = form.cleaned_data.get('telephone')
        vessel.telephone = telephone
        
        cons_lad = form.cleaned_data.get('cons_lad')
        vessel.cons_lad = cons_lad

        cons_bal = form.cleaned_data.get('cons_bal')
        vessel.cons_bal = cons_bal

        cons_por_mgo = form.cleaned_data.get('cons_por_mgo')
        vessel.cons_por_mgo = cons_por_mgo

        cons_por_ifo = form.cleaned_data.get('cons_por_ifo')
        vessel.cons_por_ifo = cons_por_ifo

        comment = form.cleaned_data.get('comment')
        vessel.comment = comment

        vessel.save()

        return redirect("VoyageCalc:vessel-list")

    context = {

VoyageCalc/templates/VoyageCalc/_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %} C-Calc -> {{ title }}
{% endblock title %}
{% block head %}

{% endblock head %}



{% block body %}

<div class="col-sm-4 col-sm-offset-4" align="center">

    <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title"><h1> {{ title }} </h1></div>
        </div>
        <div class="panel-body">
            
                        <form class="vertical" role="form" method="POST" action="{% if came_from_page %}?next={{ came_from_page }}{% endif %}" enctype="multipart/form-data">
                        
                            {% csrf_token %}
                            {{form|crispy}}
                            
                            <input type = submit class="btn btn-success" style="width:100%;" value="{{ sub_btn }}" />
                            
                        </form>

        </div>          
      </div>
}
</div>

{% block footer %}
{% endblock footer %}
{% endblock body %}

VoyageCalc/templates/VoyageCalc/chart_list.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %} List of Charts {% endblock title %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        {% if user.is_authenticated %}
        <div id="table-back" class="col-sm-8 col-sm-offset-2 col-xs-10" >
                
                <h1> List of Charts <a href="{% url 'VoyageCalc:create_chart' %}"><h4>(Add a chart)</a></h4></h1><a href="{% url 'VoyageCalc:finished-charts' %}"> (view finished charts)</a>

                
                <table class="table table-striped table-inverse">
                    <thead>
                        <tr>
                            <th>Chart No</th>
                            <th>Voyages completed</th>
                            <th>Charterer</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Countdown</th>
                            <th>Creator/Updated</th>
                            <th>Comment</th>                            
                        </tr>
                    </thead>

                    <tbody>
                        {% for object in object_list %}
                        
                            <tr>
                                <td><a href="{% url 'VoyageCalc:edit-chart' object.id %}">{{ object.chart_number }}</a></td>
                                <td>{{object.number_of_voyages }}</td>
                                <td>{{ object.charterer }}</td>
                                <td>{{ object.date_start }}</td>
                                <td>{{ object.date_end }}</td>                                
                                <td>{{ object.date_end|timeuntil }}</td>
                                {% if object.updated_by %}
                                <td>{{ object.created_by }} / {{ object.updated_by }} </td>
                                {% else %}
                                <td>{{ object.created_by.name }}</td>
                                {% endif %}
                                <td>{{ object.comment|truncatechars:50 }}</td>
                            </tr>
                          
                        {% endfor %}
                    </tbody>
                </table>

        </div>
        {% else %}
        {% include "VoyageCalc/home.html" %}
        {% endif %}
    </div>
</div>

{% endblock body %}

VoyageCalc/templates/VoyageCalc/charterer_list.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %} Charterer list {% endblock title %}

{% block body %}
<div class="container-fluid">
    <div class="row">
    {% if user.is_authenticated %}

        <div id="table-back" class="col-sm-8 col-sm-offset-2 col-xs-10" >
                
                <h1> List of Charterers <a href="{% url 'VoyageCalc:create_charterer' %}"><h4>(Add new charterer )</a></h4></h1>

                
                <table class="table table-striped table-inverse">
                    <thead>
                        <tr>
                            <th>Charterer</th>
                            <th>Contact Person</th>
                            <th>Telephone</th>
                            <th>Comment</th>

                        </tr>
                    </thead>

                    <tbody>
                        {% for object in object_list %}
                        
                            <tr>
                                <td><a href="{% url 'VoyageCalc:edit-charterer' object.id %}">{{ object.company_name }}</a></td>
                                <th>{{ object.contact_person }}</th>
                                <td>{{ object.switch_board }}</td>
                                <td>{{ object.comment|truncatechars:28 }}</td>
                            </tr>
                          
                        {% endfor %}
                    </tbody>
                </table>

        </div>
        {% else %}
        {% include "VoyageCalc/home.html" %}
        {% endif %}

    </div>
</div>

{% endblock body %}

VoyageCalc/templates/VoyageCalc/port_list.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %} Port list {% endblock title %}

{% block body %}
<div class="container-fluid">
    <div class="row">
    {% if user.is_authenticated %}

        <div id="table-back" class="col-sm-8 col-sm-offset-2 col-xs-10" >
                
                <h1> List of Ports <a href="{% url 'VoyageCalc:create_port' %}"><h4>(Add a port)</a></h4></h1>

                
                <table class="table table-striped table-inverse">
                    <thead>
                        <tr>
                            <th>Port</th>
                            <th>Contact Person</th>
                            <th>Telephone</th>
                            <th>Current charts</th>
                            <th>Comment</th>

                        </tr>
                    </thead>

                    <tbody>
                        {% for object in object_list %}
                        
                            <tr>
                                <td><a href="{% url 'VoyageCalc:edit-port' object.id %}">{{ object.port_name }}</a></td>
                                <th>{{ object.contact_person }}</th>
                                <td>{{ object.telephone }}</td>
                                <td> - under construction - </td>
                                <td>{{ object.comment|truncatechars:50 }}</td>
                            </tr>
                          
                        {% endfor %}
                    </tbody>
                </table>

        </div>
        {% else %}
        {% include "VoyageCalc/home.html" %}
        {% endif %}

    </div>
</div>

{% endblock body %}

VoyageCalc/templates/VoyageCalc/vessel_list.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %} Vessel list {% endblock title %}

{% block body %}
<div class="container-fluid">
    <div class="row">
    {% if user.is_authenticated %}

        <div id="table-back" class="col-sm-8 col-sm-offset-2 col-xs-10" >
                
                <h1> List of Vessels <a href="{% url 'VoyageCalc:create_vessel' %}"><h4>(Add a vessel)</a></h4></h1>

                
                <table class="table table-striped table-inverse">
                    <thead>
                        <tr>
                            <th>Vessel</th>
                            <th>Telephone</th>
                            <th>Usage laden</th>
                            <th>Usage ballast</th>
                            <th>Usage Port MGO</th>
                            <th>Comment</th>

                        </tr>
                    </thead>

                    <tbody>
                        {% for object in object_list %}
                        
                            <tr>
                                <td><a href="{% url 'VoyageCalc:edit-vessel' object.id %}">{{ object.vessel_name }}</a></td>
                                <th>{{ object.telephone }}</th>
                                <th>{{ object.cons_lad }}</th>
                                <th>{{ object.cons_bal }}</th>
                                <th>{{ object.cons_por_mgo }}</th>
                                <td>{{ object.comment|truncatechars:50 }}</td>
                            </tr>
                          
                        {% endfor %}
                    </tbody>
                </table>

        </div>
        {% else %}
        {% include "VoyageCalc/home.html" %}
        {% endif %}

    </div>
</div>

{% endblock body %}

VoyageCalc/templates/VoyageCalc/voyage_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %} C-Calc -> {{ title }}
{% endblock title %}
{% block head %}

{% endblock head %}



{% block body %}
<div class="col-sm-4 col-sm-offset-4" align="center">
    <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title"><h1> {{ title }} </h1></div>
        </div>
        <div class="panel-body">
            
            <form class="vertical" role="form" method="POST" action="" enctype="multipart/form-data">
            
                <h3><a href="{% url 'VoyageCalc:add_income' voyage.id %}?from={{ request.path|urlencode }}"><span class="glyphicon glyphicon-plus" style="color:green;"></span></a> Incomes | Expenses <a href="{% url 'VoyageCalc:add_cost' voyage.id %}?from={{ request.path|urlencode }}"><span class="glyphicon glyphicon-minus" style="color:red;"></span></a></h3>
                <div class="col-sm-12">
                <div class="col-sm-6">
                  <table class="table table-bordered table-condensed">
                    <thead>
                      <tr>
                        <th>What</th>
                        <th>Amount</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for income in incomes %}
                      <tr style="color:green;">
                        <td>{{ income.income_type }}</td>
                        <td>{{ income.income_nok }}</td>
                      </tr>
                    {% endfor %}
                    <tr>
                    <td>Gross Fr.</td><td> {{ voyage.voyage_incomes }} </td>
                    </tr>
                    </tbody>
                  </table>
                  </div>
                  <div class="col-sm-6">
                    <table class="table table-bordered table-condensed">
                    <thead>
                      <tr>
                        <th>What</th>
                        <th>Amount</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for cost in costs %}
                      <tr style="color:red;">
                        <td>{{ cost.cost_type }}</td>
                        <td>{{ cost.cost_nok }}</td>
                      </tr>

                    {% endfor %}
                    <tr style="color:red;"><td>Bunkers</td><td>{{ voyage.bunkers }}</td></tr>
                    <tr style="color:red;"><td>Commission</td><td>{{ voyage.commission }}</td></tr>
                    <tr>
                    <td>Total Exp.</td><td> {{ voyage.voyage_costs }} </td>
                    </tr>

                    </tbody>
                  </table>
                  
                  </div>
                  <div class="col-sm-12" style="text-align:center;">
                           <p style="font-size:25px; font-weight: bold; color:{{ voyage.color_net }};"> Net Freight: {{ voyage.net_freight }}</p>
                  </div>
                  </div>


                  {% csrf_token %}
                {{form|crispy}}
                <hr>
                </div>            
                <p>   
                </p>
                <hr>
                <input type = submit class="btn btn-success" style="width:100%;" value="{{ sub_btn }}" />
            </form>

        </div>          
      </div>
</div>

{% block footer %}
{% endblock footer %}
{% endblock body %}

VoyageCalc/templates/VoyageCalc/voyage_list.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %} Voyage list {% endblock title %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        {% if user.is_authenticated %}

        <div id="table-back" class="col-sm-10 col-sm-offset-1 col-xs-10" >
                
                <h1> Completed Voyages <a href="{% url 'VoyageCalc:create_voyage' %}"><h4>(Register new voyage)</a></h4></h1>

                
                <table class="table table-striped table-inverse">
                    <thead>
                        <tr>
                            <th>Voyage No</th>
                            <th>Vessel</th>
                            <th>Charterer</th>
                            <th>Gross Freight</th>
                            <th>Commission</th>
                            <th>Bunkers</th>
                            <th>Net Freight</th>
                            <th>Tot. Days</th>
                            <th>Voy TC Eq</th>
                            <th>Chart TC</th>
                            <th>Reg by</th>                
                        </tr>
                    </thead>

                    <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td><a href="{% url 'VoyageCalc:edit-voyage' object.id %}">{{ object.voyage_number }}</a></td>
                                <td>{{ object.vessel }}</td>
                                <td>{{ object.chart.charterer|truncatechars:7 }}</td>
                                <td>{{ object.voyage_incomes }}</td>
                                <td>{{ object.commission }}</td>
                                <td>{{ object.bunkers }}</td>
                                <td>{{ object.net_freight }}</td>
                                <td>{{ object.total_days }}</td>
                                {% if object.over_chart %}<td style="color:green;">{% else %}<td>{% endif %}{{ object.tc_equiv }}</td>
                                <td>{{ object.chart_avg_tc}} </td>
                                <td></td>
                            </tr>
                          
                        {% endfor %}
                    </tbody>
                </table>

        </div>
        {% else %}
        {% include "VoyageCalc/home.html" %}
        {% endif %}

    </div>
</div>

{% endblock body %}